title: 'atharvakokane.github.io'
baseurl: "/"
url: "https:/atharvakokane.github.io"

header_pages:
  - index.md
  - blog.md
  - contact.md
  - resume.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
