title: 'atharvakokane.github.io'
baseurl: "/"
url: "https://atharvakokane.github.io"
google_analytics: G-NPKT7VPC3B

header_pages:
  - index.md
  - blog.md
  - projects.md
  - research.md
  - contact.md
  - resume.md

style: dark

plugins:
  - jekyll-remote-theme

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

mathjax: true

remote_theme: b2a3e8/jekyll-theme-console
